import Amala from '../assets/Images-Order-management/Amala&Ewedu.jpg'; 
import BeansPlantain from '../assets/Images-Order-management/Beans&Plantain.jpg';
import Egusi from '../assets/Images-Order-management/Egusi&Poundo.jpg'; 
import EwaAgoyin from '../assets/Images-Order-management/EwaAgoyin.jpg'; 
import FriedRice from '../assets/Images-Order-management/Friedrice.jpg'; 
import GhanaJollof from '../assets/Images-Order-management/GhanaJollof.jpg'; 
import Oha from '../assets/Images-Order-management/Oha.jpg'; 
import Waakye from '../assets/Images-Order-management/Waakye.jpg'; 


const FoodList = [
    {
        id: 1,
        logo: "HA",
        name: "Hafsat Abdul",
        orderCode: 24071,
        date: "12-08-2023",
        time: "11:28 PM",
        address: "49 Featherstone Street, EC1Y 8SY, London",
        Foodname1: "Amala & Ewedu",
        Desc1: "Amala, Ewedu and Gbegiri",
        img1: Amala,
        Price1: 20,
        Qty1: 2,
        Status1: "Delivered",
        Foodname2: "Fried Rice & Chicken",
        Desc2: "Fried Rice, Salad and Chicken",
        img2: FriedRice,
        Price2: 18,
        Qty2: 2,
        Status2: "Delivered",
        items: 4,
        Total: 38,
    },


    {
        id: 2,
        logo: "CE",
        name: "Chidinma Eze",
        orderCode: 24072,
        date: "13-08-2023",
        time: "12:30 PM",
        address: "Studio 36 Cox Crossing, Maxborough",
        Foodname1: "Egusi & Poundo",
        Desc1: "Egusi Soup and Pounded Yam",
        img1: Egusi,
        Price1: 20,
        Qty1: 2,
        Status1: "Delivered",
        Foodname2: "Beans & Plantain",
        Desc2: "Beans Porridge and Plantain",
        img2: BeansPlantain,
        Price2: 10,
        Qty2: 1,
        Status2: "Declined",
        items: 3,
        Total: 30,
    },

    {
        id: 3,
        logo: "DK",
        name: "David Kuti",
        orderCode: 24073,
        date: "14-08-2023",
        time: "1:30 PM",
        address: "11B, Brace Avenue, United Kingdom",
        Foodname1: "Ghana Jollof & Beef",
        Desc1: "Spicy Ghana Jollof rice and Beef",
        img1: GhanaJollof,
        Price1: 15,
        Qty1: 1,
        Status1: "Delivered",
        Foodname2: "Ewa Agoyin & Fries",
        Desc2: "Ewa Agoyin and Fried plantain",
        img2: EwaAgoyin,
        Price2: 10,
        Qty2: 1,
        Status2: "Delivered",
        items: 2,
        Total: 25,
    },

    {
        id: 4,
        logo: "CE",
        name: "Cherechi Babalola",
        orderCode: 24074,
        date: "15-08-2023",
        time: "10:30 AM",
        address: "62, Ermin Street, Yalding, UK",
        Foodname1: "Ghanian Waakye",
        Desc1: "Ghanian Waakye and stew",
        img1: Waakye,
        Price1: 20,
        Qty1: 2,
        Status1: "Declined",
        Foodname2: "Fried Rice & Chicken",
        Desc2: "Fried Rice, Salad and Chicken",
        img2: FriedRice,
        Price2: 18,
        Qty2: 1,
        Status2: "Delivered",
        items: 3,
        Total: 38,
    },

    {
        id: 5,
        logo: "ST",
        name: "Saidat Toluwani",
        orderCode: 24075,
        date: "16-08-2023",
        time: "10:30 AM",
        address: "16 Whatlington Road, Cove, United KIngdom",
        Foodname1: "Beans & Plantain",
        Desc1: "Beans Porridge and Plantain",
        img1: BeansPlantain,
        Price1: 20,
        Qty1: 1,
        Status1: "Declined",
        Foodname2: "Oha soup & Semo",
        Desc2: "Oha soup, semo and meat",
        img2: Oha,
        Price2: 20,
        Qty2: 2,
        Status2: "Declined",
        items: 3,
        Total: 40,
    },

    {
        id: 6,
        logo: "EI",
        name: "Emmanuel Ifeoma",
        orderCode: 24076,
        date: "17-08-2023",
        time: "6:30 PM",
        address: "77 Boar Lane, Shauntullich, United Kingdom",
        Foodname1: "Jollof Rice & Chicken",
        Desc1: "Spicy Jollof rice and Chicken",
        img1: GhanaJollof,
        Price1: 20,
        Qty1: 2,
        Status1: "Delivered",
        Foodname2: "Egusi & Poundo",
        Desc2: "Egusi soup and poundo",
        img2: Egusi,
        Price2: 10,
        Qty2: 2,
        Status2: "Delivered",
        items: 4,
        Total: 30,
    },

    {
        id: 7,
        logo: "TO",
        name: "Taofeekat Olorunkosebi",
        orderCode: 24077,
        date: "18-08-2023",
        time: "2:30 PM",
        address: "17 Pendwyallt Rd, Burston, UK",
        Foodname1: "Amala & Ewedu",
        Desc1: "Amala, Ewedu and Gbegiri",
        img1: Amala,
        Price1: 20,
        Qty1: 2,
        Status1: "Declined",
        Foodname2: "Beans & Plantain",
        Desc2: "Beans Porridge and Plantain",
        img2: BeansPlantain,
        Price2: 10,
        Qty2: 1,
        Status2: "Delivered",
        items: 3,
        Total: 30,
        showDetails: false,
    },

    {
        id: 8,
        logo: "OJ",
        name: "Oluwaseyi Jimoh",
        orderCode: 24078,
        date: "19-08-2023",
        time: "5:30 PM",
        address: "62 Nenthead Road, Howe, United Kingdom",
        Foodname1: "Ghanian Waakye",
        Desc1: "Ghanian Waakye and stew",
        img1: Waakye,
        Price1: 20,
        Qty1: 2,
        Status1: "Delivered",
        Foodname2: "Fried Rice & Chicken",
        Desc2: "Fried Rice, Salad and Chicken",
        img2: FriedRice,
        Price2: 18,
        Qty2: 2,
        Status2: "Delivered",
        items: 4,
        Total: 38,
    },

    
    
]

export default FoodList;