export const Countries = [
    { id: "AFG", name: "Afghanistan", code: "+93" },
    { id: "ALA", name: "Åland Islands", code: "+358" },
    { id: "ALB", name: "Albania", code: "+355" },
    { id: "DZA", name: "Algeria", code: "+213" },
    { id: "ASM", name: "American Samoa", code: "+1" },
    { id: "AND", name: "Andorra", code: "+376" },
    { id: "AGO", name: "Angola", code: "+244" },
    { id: "AIA", name: "Anguilla", code: "+1" },
    { id: "ATA", name: "Antarctica", code: "+672" },
    { id: "ATG", name: "Antigua and Barbuda", code: "+1" },
    { id: "ARG", name: "Argentina", code: "+54" },
    { id: "ARM", name: "Armenia", code: "+374" },
    { id: "ABW", name: "Aruba", code: "+297" },
    { id: "AUS", name: "Australia", code: "+61" },
    { id: "AUT", name: "Austria", code: "+43" },
    { id: "AZE", name: "Azerbaijan", code: "+994" },
    { id: "BHS", name: "Bahamas", code: "+1" },
    { id: "BHR", name: "Bahrain", code: "+973" },
    { id: "BGD", name: "Bangladesh", code: "+880" },
    { id: "BRB", name: "Barbados", code: "+1" },
    { id: "BLR", name: "Belarus", code: "+375" },
    { id: "BEL", name: "Belgium", code: "+32" },
    { id: "BLZ", name: "Belize", code: "+501" },
    { id: "BEN", name: "Benin", code: "+229" },
    { id: "BMU", name: "Bermuda", code: "+1" },
    { id: "BTN", name: "Bhutan", code: "+975" },
    { id: "BOL", name: "Bolivia (Plurinational State of)", code: "+591" },
    { id: "BES", name: "Bonaire, Sint Eustatius and Saba", code: "+599" },
    { id: "BIH", name: "Bosnia and Herzegovina", code: "+387" },
    { id: "BWA", name: "Botswana", code: "+267" },
    { id: "BVT", name: "Bouvet Island", code: "" },
    { id: "BRA", name: "Brazil", code: "+55" },
    { id: "IOT", name: "British Indian Ocean Territory", code: "+246" },
    { id: "BRN", name: "Brunei Darussalam", code: "+673" },
    { id: "BGR", name: "Bulgaria", code: "+359" },
    { id: "BFA", name: "Burkina Faso", code: "+226" },
    { id: "BDI", name: "Burundi", code: "+257" },
    { id: "CPV", name: "Cabo Verde", code: "+238" },
    { id: "KHM", name: "Cambodia", code: "+855" },
    { id: "CMR", name: "Cameroon", code: "+237" },
    { id: "CAN", name: "Canada", code: "+1" },
    { id: "CYM", name: "Cayman Islands", code: "+1" },
    { id: "CAF", name: "Central African Republic", code: "+236" },
    { id: "TCD", name: "Chad", code: "+235" },
    { id: "CHL", name: "Chile", code: "+56" },
    { id: "CHN", name: "China", code: "+86" },
    { id: "CXR", name: "Christmas Island", code: "+61" },
    { id: "CCK", name: "Cocos (Keeling) Islands", code: "+61" },
    { id: "COL", name: "Colombia", code: "+57" },
    { id: "COM", name: "Comoros", code: "+269" },
    { id: "COG", name: "Congo", code: "+242" },
    { id: "COD", name: "Congo, Democratic Republic of the", code: "+243" },
    { id: "COK", name: "Cook Islands", code: "+682" },
    { id: "CRI", name: "Costa Rica", code: "+506" },
    { id: "CIV", name: "Côte d'Ivoire", code: "+225" },
    { id: "HRV", name: "Croatia", code: "+385" },
    { id: "CUB", name: "Cuba", code: "+53" },
    { id: "CUW", name: "Curaçao", code: "+599" },
    { id: "CYP", name: "Cyprus", code: "+357" },
    { id: "CZE", name: "Czechia", code: "+420" },
    { id: "DNK", name: "Denmark", code: "+45" },
    { id: "DJI", name: "Djibouti", code: "+253" },
    { id: "DMA", name: "Dominica", code: "+1" },
    { id: "DOM", name: "Dominican Republic", code: "+1" },
    { id: "ECU", name: "Ecuador", code: "+593" },
    { id: "EGY", name: "Egypt", code: "+20" },
    { id: "SLV", name: "El Salvador", code: "+503" },
    { id: "GNQ", name: "Equatorial Guinea", code: "+240" },
    { id: "ERI", name: "Eritrea", code: "+291" },
    { id: "EST", name: "Estonia", code: "+372" },
    { id: "SWZ", name: "Eswatini", code: "+268" },
    { id: "ETH", name: "Ethiopia", code: "+251" },
    { id: "FLK", name: "Falkland Islands (Malvinas)", code: "" },
    { id: "FRO", name: "Faroe Islands", code: "+298" },
    { id: "FJI", name: "Fiji", code: "+679" },
    { id: "FIN", name: "Finland", code: "+358" },
    { id: "FRA", name: "France", code: "+33" },
    { id: "GUF", name: "French Guiana", code: "+594" },
    { id: "PYF", name: "French Polynesia", code: "+689" },
    { id: "ATF", name: "French Southern Territories", code: "" },
    { id: "GAB", name: "Gabon", code: "+241" },
    { id: "GMB", name: "Gambia", code: "+220" },
    { id: "GEO", name: "Georgia", code: "+995" },
    { id: "DEU", name: "Germany", code: "+49" },
    { id: "GHA", name: "Ghana", code: "+233" },
    { id: "GIB", name: "Gibraltar", code: "+350" },
    { id: "GRC", name: "Greece", code: "+30" },
    { id: "GRL", name: "Greenland", code: "+299" },
    { id: "GRD", name: "Grenada", code: "+1" },
    { id: "GLP", name: "Guadeloupe", code: "+590" },
    { id: "GUM", name: "Guam", code: "+1" },
    { id: "GTM", name: "Guatemala", code: "+502" },
    { id: "GGY", name: "Guernsey", code: "+44" },
    { id: "GIN", name: "Guinea", code: "+224" },
    { id: "GNB", name: "Guinea-Bissau", code: "+245" },
    { id: "GUY", name: "Guyana", code: "+592" },
    { id: "HTI", name: "Haiti", code: "+509" },
    { id: "HMD", name: "Heard Island and McDonald Islands", code: "" },
    { id: "VAT", name: "Holy See", code: "+379" },
    { id: "HND", name: "Honduras", code: "+504" },
    { id: "HKG", name: "Hong Kong", code: "+852" },
    { id: "HUN", name: "Hungary", code: "+36" },
    { id: "ISL", name: "Iceland", code: "+354" },
    { id: "IND", name: "India", code: "+91" },
    { id: "IDN", name: "Indonesia", code: "+62" },
    { id: "IRN", name: "Iran (Islamic Republic of)", code: "+98" },
    { id: "IRQ", name: "Iraq", code: "+964" },
    { id: "IRL", name: "Ireland", code: "+353" },
    { id: "IMN", name: "Isle of Man", code: "+44" },
    { id: "ISR", name: "Israel", code: "+972" },
    { id: "ITA", name: "Italy", code: "+39" },
    { id: "JAM", name: "Jamaica", code: "+1" },
    { id: "JPN", name: "Japan", code: "+81" },
    { id: "JEY", name: "Jersey", code: "+44" },
    { id: "JOR", name: "Jordan", code: "+962" },
    { id: "KAZ", name: "Kazakhstan", code: "+7" },
    { id: "KEN", name: "Kenya", code: "+254" },
    { id: "KIR", name: "Kiribati", code: "+686" },
    { id: "PRK", name: "Korea (Democratic People's Republic of)", code: "+850" },
    { id: "KOR", name: "Korea, Republic of", code: "+82" },
    { id: "KWT", name: "Kuwait", code: "+965" },
    { id: "KGZ", name: "Kyrgyzstan", code: "+996" },
    { id: "LAO", name: "Lao People's Democratic Republic", code: "+856" },
    { id: "LVA", name: "Latvia", code: "+371" },
    { id: "LBN", name: "Lebanon", code: "+961" },
    { id: "LSO", name: "Lesotho", code: "+266" },
    { id: "LBR", name: "Liberia", code: "+231" },
    { id: "LBY", name: "Libya", code: "+218" },
    { id: "LIE", name: "Liechtenstein", code: "+423" },
    { id: "LTU", name: "Lithuania", code: "+370" },
    { id: "LUX", name: "Luxembourg", code: "+352" },
    { id: "MAC", name: "Macao", code: "+853" },
    { id: "MKD", name: "North Macedonia", code: "+389" },
    { id: "MDG", name: "Madagascar", code: "+261" },
    { id: "MWI", name: "Malawi", code: "+265" },
    { id: "MYS", name: "Malaysia", code: "+60" },
    { id: "MDV", name: "Maldives", code: "+960" },
    { id: "MLI", name: "Mali", code: "+223" },
    { id: "MLT", name: "Malta", code: "+356" },
    { id: "MHL", name: "Marshall Islands", code: "+692" },
    { id: "MTQ", name: "Martinique", code: "+596" },
    { id: "MRT", name: "Mauritania", code: "+222" },
    { id: "MUS", name: "Mauritius", code: "+230" },
    { id: "MYT", name: "Mayotte", code: "+262" },
    { id: "MEX", name: "Mexico", code: "+52" },
    { id: "FSM", name: "Micronesia (Federated States of)", code: "+691" },
    { id: "MDA", name: "Moldova, Republic of", code: "+373" },
    { id: "MCO", name: "Monaco", code: "+377" },
    { id: "MNG", name: "Mongolia", code: "+976" },
    { id: "MNE", name: "Montenegro", code: "+382" },
    { id: "MSR", name: "Montserrat", code: "+1" },
    { id: "MAR", name: "Morocco", code: "+212" },
    { id: "MOZ", name: "Mozambique", code: "+258" },
    { id: "MMR", name: "Myanmar", code: "+95" },
    { id: "NAM", name: "Namibia", code: "+264" },
    { id: "NRU", name: "Nauru", code: "+674" },
    { id: "NPL", name: "Nepal", code: "+977" },
    { id: "NLD", name: "Netherlands", code: "+31" },
    { id: "NCL", name: "New Caledonia", code: "+687" },
    { id: "NZL", name: "New Zealand", code: "+64" },
    { id: "NIC", name: "Nicaragua", code: "+505" },
    { id: "NER", name: "Niger", code: "+227" },
    { id: "NGA", name: "Nigeria", code: "+234" },
    { id: "NIU", name: "Niue", code: "+683" },
    { id: "NFK", name: "Norfolk Island", code: "+672" },
    { id: "MNP", name: "Northern Mariana Islands", code: "+1" },
    { id: "NOR", name: "Norway", code: "+47" },
    { id: "OMN", name: "Oman", code: "+968" },
    { id: "PAK", name: "Pakistan", code: "+92" },
    { id: "PLW", name: "Palau", code: "+680" },
    { id: "PSE", name: "Palestine, State of", code: "+970" },
    { id: "PAN", name: "Panama", code: "+507" },
    { id: "PNG", name: "Papua New Guinea", code: "+675" },
    { id: "PRY", name: "Paraguay", code: "+595" },
    { id: "PER", name: "Peru", code: "+51" },
    { id: "PHL", name: "Philippines", code: "+63" },
    { id: "PCN", name: "Pitcairn", code: "+64" },
    { id: "POL", name: "Poland", code: "+48" },
    { id: "PRT", name: "Portugal", code: "+351" },
    { id: "PRI", name: "Puerto Rico", code: "+1" },
    { id: "QAT", name: "Qatar", code: "+974" },
    { id: "REU", name: "Réunion", code: "+262" },
    { id: "ROU", name: "Romania", code: "+40" },
    { id: "RUS", name: "Russian Federation", code: "+7" },
    { id: "RWA", name: "Rwanda", code: "+250" },
    { id: "BLM", name: "Saint Barthélemy", code: "+590" },
    { id: "SHN", name: "Saint Helena, Ascension and Tristan da Cunha", code: "+290" },
    { id: "KNA", name: "Saint Kitts and Nevis", code: "+1" },
    { id: "LCA", name: "Saint Lucia", code: "+1" },
    { id: "MAF", name: "Saint Martin (French part)", code: "+590" },
    { id: "SPM", name: "Saint Pierre and Miquelon", code: "+508" },
    { id: "VCT", name: "Saint Vincent and the Grenadines", code: "+1" },
    { id: "WSM", name: "Samoa", code: "+685" },
    { id: "SMR", name: "San Marino", code: "+378" },
    { id: "STP", name: "Sao Tome and Principe", code: "+239" },
    { id: "SAU", name: "Saudi Arabia", code: "+966" },
    { id: "SEN", name: "Senegal", code: "+221" },
    { id: "SRB", name: "Serbia", code: "+381" },
    { id: "SYC", name: "Seychelles", code: "+248" },
    { id: "SLE", name: "Sierra Leone", code: "+232" },
    { id: "SGP", name: "Singapore", code: "+65" },
    { id: "SXM", name: "Sint Maarten (Dutch part)", code: "+1" },
    { id: "SVK", name: "Slovakia", code: "+421" },
    { id: "SVN", name: "Slovenia", code: "+386" },
    { id: "SLB", name: "Solomon Islands", code: "+677" },
    { id: "SOM", name: "Somalia", code: "+252" },
    { id: "ZAF", name: "South Africa", code: "+27" },
    { id: "SGS", name: "South Georgia and the South Sandwich Islands", code: "" },
    { id: "SSD", name: "South Sudan", code: "+211" },
    { id: "ESP", name: "Spain", code: "+34" },
    { id: "LKA", name: "Sri Lanka", code: "+94" },
    { id: "SDN", name: "Sudan", code: "+249" },
    { id: "SUR", name: "Suriname", code: "+597" },
    { id: "SJM", name: "Svalbard and Jan Mayen", code: "+47" },
    { id: "SWE", name: "Sweden", code: "+46" },
    { id: "CHE", name: "Switzerland", code: "+41" },
    { id: "SYR", name: "Syrian Arab Republic", code: "+963" },
    { id: "TWN", name: "Taiwan", code: "+886" },
    { id: "TJK", name: "Tajikistan", code: "+992" },
    { id: "TZA", name: "Tanzania, United Republic of", code: "+255" },
    { id: "THA", name: "Thailand", code: "+66" },
    { id: "TLS", name: "Timor-Leste", code: "+670" },
    { id: "TGO", name: "Togo", code: "+228" },
    { id: "TKL", name: "Tokelau", code: "+690" },
    { id: "TON", name: "Tonga", code: "+676" },
    { id: "TTO", name: "Trinidad and Tobago", code: "+1" },
    { id: "TUN", name: "Tunisia", code: "+216" },
    { id: "TUR", name: "Turkey", code: "+90" },
    { id: "TKM", name: "Turkmenistan", code: "+993" },
    { id: "TCA", name: "Turks and Caicos Islands", code: "+1" },
    { id: "TUV", name: "Tuvalu", code: "+688" },
    { id: "UGA", name: "Uganda", code: "+256" },
    { id: "UKR", name: "Ukraine", code: "+380" },
    { id: "ARE", name: "United Arab Emirates", code: "+971" },
    { id: "GBR", name: "United Kingdom of Great Britain and Northern Ireland", code: "+44" },
    { id: "USA", name: "United States of America", code: "+1" },
    { id: "UMI", name: "United States Minor Outlying Islands", code: "" },
    { id: "URY", name: "Uruguay", code: "+598" },
    { id: "UZB", name: "Uzbekistan", code: "+998" },
    { id: "VUT", name: "Vanuatu", code: "+678" },
    { id: "VEN", name: "Venezuela (Bolivarian Republic of)", code: "+58" },
    { id: "VNM", name: "Viet Nam", code: "+84" },
    { id: "VIR", name: "Virgin Islands (British)", code: "+1" },
    { id: "VGB", name: "Virgin Islands (U.S.)", code: "+1" },
    { id: "WLF", name: "Wallis and Futuna", code: "+681" },
    { id: "ESH", name: "Western Sahara", code: "+212" },
    { id: "YEM", name: "Yemen", code: "+967" },
    { id: "ZMB", name: "Zambia", code: "+260" },
    { id: "ZWE", name: "Zimbabwe", code: "+263" }
];
